# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: LegLef1
  joint_model_group_pose: left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_left_front_1
    - joint_left_front_2
    - joint_left_front_3
    - joint_left_front_4
    - joint_left_rear_1
    - joint_left_rear_2
    - joint_left_rear_3
    - joint_left_rear_4
    - joint_right_front_1
    - joint_right_front_2
    - joint_right_front_3
    - joint_right_front_4
    - joint_right_rear_1
    - joint_right_rear_2
    - joint_right_rear_3
    - joint_right_rear_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: LegLef1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_left_front_1
      - joint_left_front_2
      - joint_left_front_3
      - joint_left_front_4
  - name: LegLeft2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_left_rear_1
      - joint_left_rear_2
      - joint_left_rear_3
      - joint_left_rear_4
  - name: LegRigh1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_right_front_1
      - joint_right_front_2
      - joint_right_front_3
  - name: LegRigh2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_right_rear_1
      - joint_right_rear_2
      - joint_right_rear_3
      - joint_right_rear_4