controller_list:
  - name: fake_Left_Leg1_controller
    joints:
      - FrontLeftJoint_1
      - FrontLeftJoint_2
      - FrontLeftJoint_3
      - FrontLeftJoint_4
initial:  # Define initial robot poses.
  - group: Left_Leg1
    pose: MaxLeft_leg1